site_name: The Joy of Programming
repo_url: https://github.com/fossunited/the-joy-of-programming
site_author: FOSS United

docs_dir: the-joy-of-programming
theme:
  name: material
  custom_dir: overrides

nav:
  - Getting Started:
    - getting-started-jp/welcome-jp.md
    - getting-started-jp/livecoding-environment-jp.md
    - getting-started-jp/hello-world-jp.md
    - getting-started-jp/numbers-jp.md
    - getting-started-jp/variables-jp.md
    - getting-started-jp/lists-jp.md

  - Drawing Shapes:
    - drawing-shapes-jp/drawing-circles-jp.md
    - drawing-shapes-jp/positioning-shapes-jp.md
    - drawing-shapes-jp/more-shapes-jp.md
    - drawing-shapes-jp/lines-and-polygons-jp.md
    - drawing-shapes-jp/adding-colors-jp.md
  - Composing New Shapes:
    - composing-new-shapes-jp/combining-shapes-jp.md
    - composing-new-shapes-jp/creating-new-shapes-jp.md
  - Repeating:
    - repeating-jp/for-loop-jp.md
    - repeating-jp/repeating-shapes-jp.md
  - Transforming:
    - transforming-jp/translate-jp.md
    - transforming-jp/rotate-jp.md
    - transforming-jp/scale-jp.md

  - Notes:
    - notes/notes.md

# nav:
#   - The Joy of Programming: index.md
#   - Getting Started:
#     - getting-started/overview.md
#     - getting-started/platform.md
#   - Drawing Shapes:
#     - drawing-shapes/basic-shapes.md
#     - drawing-shapes/the-coordinates.md
#   - Composing New Shapes:
#     - composing-new-shapes/combining-shapes.md
#     - composing-new-shapes/creating-new-shapes.md
#   - Transformations:
#     - transformations/transforming-shapes.md
#     - transformations/repetition.md
#   - Randomness:
#     - randomness/random.md
#     - randomness/generative-art.md
#   - Next Steps:
#     - next-steps/next-steps.md

# markdown_extensions:
#   - fenced_code
#   - macros
markdown_extensions:
    - admonition
    - toc:
        permalink: True
        separator: "_"
    - macros:
        registry:
          Exercise: exercise_macro:exercise_macro
          Image: exercise_macro:image_macro
          YouTubeVideo: exercise_macro:youtube_macro

extra_css:
  - assets/codemirror/lib/codemirror.css
  - assets/style.css

extra_javascript:
  - assets/codemirror/lib/codemirror.js
  - assets/codemirror/mode/python/python.js
  - assets/codemirror/keymap/sublime.js
  - assets/codemirror/addon/edit/matchbrackets.js
  - assets/codemirror/addon/comment/comment.js
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://livecode.fossunited.org/static/livecode.js
  - assets/sketch.js
  - assets/livecode-options.js
