site_name: The Joy of Programming
repo_url: https://github.com/fossunited/the-joy-of-programming
site_author: FOSS United

docs_dir: the-joy-of-programming
theme:
  name: material
  custom_dir: overrides

nav:
  - Drawing Shapes:
    - drawing-shapes-jp/drawing-simple-shapes-jp.md
    - drawing-shapes-jp/the-coordinates-jp.md

# nav:
#   - The Joy of Programming: index.md
#   - Getting Started:
#     - getting-started/overview.md
#     - getting-started/platform.md
#   - Drawing Shapes:
#     - drawing-shapes/basic-shapes.md
#     - drawing-shapes/the-coordinates.md
#   - Composing New Shapes:
#     - composing-new-shapes/combining-shapes.md
#     - composing-new-shapes/creating-new-shapes.md
#   - Transformations:
#     - transformations/transforming-shapes.md
#     - transformations/repetition.md
#   - Randomness:
#     - randomness/random.md
#     - randomness/generative-art.md
#   - Next Steps:
#     - next-steps/next-steps.md

# markdown_extensions:
#   - fenced_code
#   - macros
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
    - macros:
        registry:
          Exercise: exercise_macro:exercise_macro


extra_css:
  - assets/codemirror/lib/codemirror.css
  - assets/style.css

extra_javascript:
  - assets/codemirror/lib/codemirror.js
  - assets/codemirror/mode/python/python.js
  - assets/codemirror/keymap/sublime.js
  - assets/codemirror/addon/edit/matchbrackets.js
  - assets/codemirror/addon/comment/comment.js
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://livecode.fossunited.org/static/livecode.js
  - assets/sketch.js
  - assets/livecode-options.js
